### ISSUE TITLE
issue with n+V (n + shift + V)

### ISSUE THREAD

**Issue by girishadurrel** [ctrlpvim/ctrlp.vim#360] opened 2017-04-09 10:23 UTC
Once I use ctrl+p and open a new file on a different tab by pressing "t", the n+V selects more than "n" lines. This issue does not happen when I use :tabnew and open a file or when I open the file on the same tab using ctrl+p (pressing enter and not "t")

It only happens if the open file is a source file (in my case .java). It does not happen when I open a normal text file.

**Comment by girishadurrel** [comment] 2017-04-11 05:27
further testing proved that this is not an issue with ctrlp. therefore closing the issue

**Comment by muffinmad** [comment] 2017-04-11 07:50
I can reproduce this issue by opening and close CtrlP window.

**Comment by girishadurrel** [comment] 2017-04-11 10:12
Since another user found the same issue I will reopen the issue

**Comment by mattn** [comment] 2017-04-26 03:17
Could you please tell me the simple way to repro?

**Comment by muffinmad** [comment] 2017-04-26 09:10
0. Populate buffer with lines of text e.g. `iabc<ESC>yy10p`
1. `3V` select 3 lines
2. `:CtrlPBuffer` then `<ESC>` to close CtrlP
3. `3V` now select more than 3 lines

**Comment by girishadurrel** [comment] 2017-04-26 09:33
Can confirm that the above simple steps reproduces the problem to me as well. I can reproduce this on vim version 7.4.1689 (Linux Mint 18) and version 7.4.52 (Ubuntu 14.04)

**Comment by girishadurrel** [comment] 2017-04-26 09:47
removed all the other plugins and cleared up my .vimrc which only had the line to execute pathogen "execute pathogen#infect()" 
the problem is still producible

**Comment by mattn** [comment] 2017-04-26 10:12
This is not depend on CtrlP. See `:help characterwise-visual`.

```
						*v* *characterwise-visual*
[count]v		Start Visual mode per character.
			With [count] select the same number of characters or
			lines as used for the last Visual operation, but at
			the current cursor position, multiplied by [count].
			When the previous Visual operation was on a block both
			the width and height of the block are multiplied by
			[count].
			When there was no previous Visual operation [count]
			characters are selected.  This is like moving the
			cursor right N * [count] characters.  One less when
			'selection' is not "exclusive".
```
Second `3V` mean "do three time for last visual operation" not 3 lines.
 i.e. 3 x 3 v.

**Comment by mattn** [comment] 2017-04-26 10:16
FYI. way to reproduce without CtrlP.
```
iabc<ESC>yy10p
3V:<ESC>3V
```

**Comment by muffinmad** [comment] 2017-04-26 11:17
Without CtrlP:
`3V` - 3 lines selected
<ESC> - no selection
`3V` - 3 lines selected

**Comment by mattn** [comment] 2017-04-26 13:02
because it don't do any operations. so you don't have previous operation.

**Comment by muffinmad** [comment] 2017-04-26 13:13
But after opening CtrlP window with `:CtrlPBuffer` and closing it by `<ESC>` `3V` selects more than three lines.
In this comment https://github.com/ctrlpvim/ctrlp.vim/issues/360#issuecomment-297309803 I'm forgot to mention that I cleared visual selection by ESC after each `3V`

**Comment by mattn** [comment] 2017-04-26 15:06
No, you can reproduce with only typing `:` as I mentioned above.

**Comment by mattn** [comment] 2017-04-26 15:08
And this is expected behavior of Vim. As I wrote in above, `3V` is not `select 3 line`. This is `do 3 times previous visual operaiton`.

**Comment by muffinmad** [comment] 2017-04-26 15:36
Please take a look at this screencast
<img src="https://i.imgur.com/wg2XHsV.gif">

**Comment by mattn** [comment] 2017-04-26 16:33
Ah, I just understand what you mean. Yes, seems to be problem.

**Closed** 2017-04-26 16:42 UTC

**Comment by girishadurrel** [comment] 2017-04-26 23:33
Thank guys!!!
