### ISSUE TITLE
Weird tags (<bi>, <bn>, <bp>) in CtrlPBuffer list

### ISSUE THREAD

**Issue by danielbprice** [ctrlpvim/ctrlp.vim#419] opened 2018-02-01 23:04 UTC
This has to be user error but I'm stumped.  I'm new to ctrl-p, as I'm looking for something to help manage buffers more easily.  When I run `:CtrlPBuffer` the output is "marked up" with HTML-type tags.  I don't know why, or how to make them go away.  I'm on debian stretch with vim version 8.0.707.  Here is what it looks like:

![screen shot 2018-02-01 at 2 54 05 pm](https://user-images.githubusercontent.com/2693615/35707842-38843d00-0760-11e8-8ab2-4e066d97e2f8.png)

I've cut my .vimrc back to an empty file and the problem persists.

I'm running ctrlp from commit:

```
commit 88abbcb926a415b789ff648cbdc86ed4b353bfc1
Merge: 8db39ec d62bbc5
Author: mattn <mattn.jp@gmail.com>
Date:   Mon Jan 15 18:31:49 2018 +0900
```

I'm using vim8 'pack' package management, and this is the only plugin I have.

**Comment by mattn** [comment] 2018-04-03 06:08
Do you use ctrlp_user_command?

**Comment by npupko** [comment] 2018-09-04 09:16
@mattn I have the same issue with simple init.vim:
```vim
call plug#begin()
  Plug 'ctrlpvim/ctrlp.vim'
call plug#end()
syntax off
```

It becomes difficult to use the plugin. Maybe I can help with solving this problem?

![image](https://user-images.githubusercontent.com/5938539/45022099-0698be80-b03c-11e8-8847-1f3f8acca98c.png)

**Comment by mattn** [comment] 2018-09-07 16:30
Could you please show me your tags file?

**Comment by npupko** [comment] 2018-09-07 16:53
@mattn I do not quite understand how this is connected. Are you talking about the files that I generate with the `ctags` command? I have different files for different projects (obviously). Or we are talking about different things?

**Comment by mattn** [comment] 2018-09-07 17:10
I still not understand how to reproduce.

**Comment by mattn** [comment] 2018-09-08 01:09
I don't see it.  Do you use neovim? What version?

**Comment by npupko** [comment] 2018-09-08 19:10
@mattn 
```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/build/config -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/build/src/nvim/auto -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui
```

**Comment by danielbprice** [comment] 2018-09-11 04:04
@npupko I feel your pain.  I reported this originally, and for me it doesn't happen anymore.  (I'm still on debian stretch, still running vim 8.0.707).  I'm not sure what I changed, because I didn't notice right away when it got fixed.  For what it's worth, for a long time I had my ~/.vim behind a symlink, and that caused a lot of weird and subtle problems for several different plugins.  So if by chance you have that, I'd try getting rid of it.

**Comment by mattn** [comment] 2018-09-11 04:31
@npupko do you use older version?

it seems to be fixed in https://github.com/ctrlpvim/ctrlp.vim/issues/445 already.

**Comment by npupko** [comment] 2018-09-12 09:55
@mattn As I said above, I use only latest versions
https://github.com/ctrlpvim/ctrlp.vim/issues/419#issuecomment-418298623

**Comment by mattn** [comment] 2018-09-13 02:00
@npupko I mean what version of neovim do you use.

**Comment by npupko** [comment] 2018-09-13 08:58
@mattn I use Neovim 0.3.1
https://github.com/ctrlpvim/ctrlp.vim/issues/419#issuecomment-419666217

**Comment by mattn** [comment] 2018-09-13 16:00
I tried this on vim8 and neovim but not reproduce.

**Comment by mattn** [comment] 2018-09-13 16:01
Ah, now I can reproduce this.

**Comment by mattn** [comment] 2018-09-13 16:16
Now addressed on https://github.com/ctrlpvim/ctrlp.vim/pull/479

**Closed** 2018-09-13 16:19 UTC
